project: 
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: kosrae.qmd
        text: My Island Home

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual

